/*
 * SPDX-FileCopyrightText: Copyright 2019-2024, 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ETHOSU_PMU_TYPES_H
#define ETHOSU_PMU_TYPES_H

/*****************************************************************************
 * Defines
 *****************************************************************************/
#ifndef ETHOSU_MULTI_DEVICE
#ifdef ETHOSU85
#define ETHOSU_PMU_NCOUNTERS 8
#else
#define ETHOSU_PMU_NCOUNTERS 4
#endif
#endif

#define ETHOSU_PMU_CNT1_Msk (1UL << 0)
#define ETHOSU_PMU_CNT2_Msk (1UL << 1)
#define ETHOSU_PMU_CNT3_Msk (1UL << 2)
#define ETHOSU_PMU_CNT4_Msk (1UL << 3)
#define ETHOSU_PMU_CNT5_Msk (1UL << 4)
#define ETHOSU_PMU_CNT6_Msk (1UL << 5)
#define ETHOSU_PMU_CNT7_Msk (1UL << 6)
#define ETHOSU_PMU_CNT8_Msk (1UL << 7)

#define ETHOSU_PMU_CCNT_Msk (1UL << 31)

/*****************************************************************************
 * Types
 *****************************************************************************/

/** \brief Abstraction layer list of all combined PMU events for all devices
 *
 * Note: These values are symbolic. Actual HW-values may change. I.e. always use API
 *       to set/get actual event-type value. Not all device types supports all
 *       event types.
 * */
enum ethosu_pmu_event_type
{
    ETHOSU_PMU_AO_ACTIVE = 0,
    ETHOSU_PMU_AO_ACTIVE_16BIT,
    ETHOSU_PMU_AO_ACTIVE_8BIT,
    ETHOSU_PMU_AO_STALLED_BY_AB,
    ETHOSU_PMU_AO_STALLED_BY_AB_OR_CB,
    ETHOSU_PMU_AO_STALLED_BY_ACC,
    ETHOSU_PMU_AO_STALLED_BY_ACC_IB,
    ETHOSU_PMU_AO_STALLED_BY_BS,
    ETHOSU_PMU_AO_STALLED_BY_BS_OR_OB,
    ETHOSU_PMU_AO_STALLED_BY_CB,
    ETHOSU_PMU_AO_STALLED_BY_IB,
    ETHOSU_PMU_AO_STALLED_BY_OB,
    ETHOSU_PMU_AO_STALLED_BY_OFMP,
    ETHOSU_PMU_AO_STALLED_BY_OFMP_OB,
    ETHOSU_PMU_AXI0_ENABLED_CYCLES,
    ETHOSU_PMU_AXI0_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_AXI0_RD_STALL_LIMIT,
    ETHOSU_PMU_AXI0_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_AXI0_RD_TRANS_COMPLETED,
    ETHOSU_PMU_AXI0_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_AXI0_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_AXI0_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_AXI0_WR_STALL_LIMIT,
    ETHOSU_PMU_AXI0_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_AXI0_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_AXI0_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_AXI0_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_AXI1_ENABLED_CYCLES,
    ETHOSU_PMU_AXI1_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_AXI1_RD_STALL_LIMIT,
    ETHOSU_PMU_AXI1_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_AXI1_RD_TRANS_COMPLETED,
    ETHOSU_PMU_AXI1_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_AXI1_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_AXI1_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_AXI1_WR_STALL_LIMIT,
    ETHOSU_PMU_AXI1_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_AXI1_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_AXI1_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_AXI1_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_AXI_LATENCY_1024,
    ETHOSU_PMU_AXI_LATENCY_128,
    ETHOSU_PMU_AXI_LATENCY_256,
    ETHOSU_PMU_AXI_LATENCY_32,
    ETHOSU_PMU_AXI_LATENCY_512,
    ETHOSU_PMU_AXI_LATENCY_64,
    ETHOSU_PMU_AXI_LATENCY_ANY,
    ETHOSU_PMU_CC_STALLED_ON_BLOCKDEP,
    ETHOSU_PMU_CC_STALLED_ON_SHRAM_RECONFIG,
    ETHOSU_PMU_CYCLE,
    ETHOSU_PMU_ECC_AO_CB,
    ETHOSU_PMU_ECC_AO_LUT,
    ETHOSU_PMU_ECC_AO_OB,
    ETHOSU_PMU_ECC_DMA,
    ETHOSU_PMU_ECC_MAC_AB,
    ETHOSU_PMU_ECC_MAC_IB,
    ETHOSU_PMU_ECC_SB0,
    ETHOSU_PMU_ECC_SB1,
    ETHOSU_PMU_EXT0_ENABLED_CYCLES,
    ETHOSU_PMU_EXT0_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_EXT0_RD_STALL_LIMIT,
    ETHOSU_PMU_EXT0_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_EXT0_RD_TRANS_COMPLETED,
    ETHOSU_PMU_EXT0_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_EXT0_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_EXT0_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_EXT0_WR_STALL_LIMIT,
    ETHOSU_PMU_EXT0_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_EXT0_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_EXT0_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_EXT0_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_EXT1_ENABLED_CYCLES,
    ETHOSU_PMU_EXT1_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_EXT1_RD_STALL_LIMIT,
    ETHOSU_PMU_EXT1_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_EXT1_RD_TRANS_COMPLETED,
    ETHOSU_PMU_EXT1_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_EXT1_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_EXT1_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_EXT1_WR_STALL_LIMIT,
    ETHOSU_PMU_EXT1_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_EXT1_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_EXT1_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_EXT1_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_EXT_ENABLED_CYCLES,
    ETHOSU_PMU_EXT_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_EXT_RD_STALL_LIMIT,
    ETHOSU_PMU_EXT_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_EXT_RD_TRANS_COMPLETED,
    ETHOSU_PMU_EXT_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_EXT_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_EXT_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_EXT_WR_STALL_LIMIT,
    ETHOSU_PMU_EXT_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_EXT_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_EXT_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_EXT_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_MAC_ACTIVE,
    ETHOSU_PMU_MAC_ACTIVE_16BIT,
    ETHOSU_PMU_MAC_ACTIVE_32BIT,
    ETHOSU_PMU_MAC_ACTIVE_8BIT,
    ETHOSU_PMU_MAC_DPU_ACTIVE,
    ETHOSU_PMU_MAC_STALLED_BY_ACC,
    ETHOSU_PMU_MAC_STALLED_BY_IB,
    ETHOSU_PMU_MAC_STALLED_BY_INT_ACC,
    ETHOSU_PMU_MAC_STALLED_BY_INT_W,
    ETHOSU_PMU_MAC_STALLED_BY_W,
    ETHOSU_PMU_MAC_STALLED_BY_WD,
    ETHOSU_PMU_MAC_STALLED_BY_WD_ACC,
    ETHOSU_PMU_MAC_STALLED_BY_W_OR_ACC,
    ETHOSU_PMU_NO_EVENT,
    ETHOSU_PMU_NPU_ACTIVE,
    ETHOSU_PMU_NPU_IDLE,
    ETHOSU_PMU_SRAM0_ENABLED_CYCLES,
    ETHOSU_PMU_SRAM0_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_SRAM0_RD_STALL_LIMIT,
    ETHOSU_PMU_SRAM0_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM0_RD_TRANS_COMPLETED,
    ETHOSU_PMU_SRAM0_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM0_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_SRAM0_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_SRAM0_WR_STALL_LIMIT,
    ETHOSU_PMU_SRAM0_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM0_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_SRAM0_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_SRAM0_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM1_ENABLED_CYCLES,
    ETHOSU_PMU_SRAM1_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_SRAM1_RD_STALL_LIMIT,
    ETHOSU_PMU_SRAM1_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM1_RD_TRANS_COMPLETED,
    ETHOSU_PMU_SRAM1_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM1_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_SRAM1_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_SRAM1_WR_STALL_LIMIT,
    ETHOSU_PMU_SRAM1_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM1_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_SRAM1_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_SRAM1_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM2_ENABLED_CYCLES,
    ETHOSU_PMU_SRAM2_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_SRAM2_RD_STALL_LIMIT,
    ETHOSU_PMU_SRAM2_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM2_RD_TRANS_COMPLETED,
    ETHOSU_PMU_SRAM2_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM2_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_SRAM2_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_SRAM2_WR_STALL_LIMIT,
    ETHOSU_PMU_SRAM2_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM2_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_SRAM2_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_SRAM2_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM3_ENABLED_CYCLES,
    ETHOSU_PMU_SRAM3_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_SRAM3_RD_STALL_LIMIT,
    ETHOSU_PMU_SRAM3_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM3_RD_TRANS_COMPLETED,
    ETHOSU_PMU_SRAM3_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM3_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_SRAM3_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_SRAM3_WR_STALL_LIMIT,
    ETHOSU_PMU_SRAM3_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM3_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_SRAM3_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_SRAM3_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM_ENABLED_CYCLES,
    ETHOSU_PMU_SRAM_RD_DATA_BEAT_RECEIVED,
    ETHOSU_PMU_SRAM_RD_STALL_LIMIT,
    ETHOSU_PMU_SRAM_RD_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM_RD_TRANS_COMPLETED,
    ETHOSU_PMU_SRAM_RD_TRAN_REQ_STALLED,
    ETHOSU_PMU_SRAM_WR_DATA_BEAT_STALLED,
    ETHOSU_PMU_SRAM_WR_DATA_BEAT_WRITTEN,
    ETHOSU_PMU_SRAM_WR_STALL_LIMIT,
    ETHOSU_PMU_SRAM_WR_TRANS_ACCEPTED,
    ETHOSU_PMU_SRAM_WR_TRANS_COMPLETED_M,
    ETHOSU_PMU_SRAM_WR_TRANS_COMPLETED_S,
    ETHOSU_PMU_SRAM_WR_TRAN_REQ_STALLED,
    ETHOSU_PMU_WD_ACTIVE,
    ETHOSU_PMU_WD_PARSE_ACTIVE,
    ETHOSU_PMU_WD_PARSE_ACTIVE_SC0,
    ETHOSU_PMU_WD_PARSE_ACTIVE_SC1,
    ETHOSU_PMU_WD_PARSE_ACTIVE_SC2,
    ETHOSU_PMU_WD_PARSE_ACTIVE_SC3,
    ETHOSU_PMU_WD_PARSE_STALLED,
    ETHOSU_PMU_WD_PARSE_STALLED_IN,
    ETHOSU_PMU_WD_PARSE_STALLED_OUT,
    ETHOSU_PMU_WD_PARSE_STALL_IN_SC0,
    ETHOSU_PMU_WD_PARSE_STALL_IN_SC1,
    ETHOSU_PMU_WD_PARSE_STALL_IN_SC2,
    ETHOSU_PMU_WD_PARSE_STALL_IN_SC3,
    ETHOSU_PMU_WD_PARSE_STALL_OUT_SC0,
    ETHOSU_PMU_WD_PARSE_STALL_OUT_SC1,
    ETHOSU_PMU_WD_PARSE_STALL_OUT_SC2,
    ETHOSU_PMU_WD_PARSE_STALL_OUT_SC3,
    ETHOSU_PMU_WD_PARSE_STALL_SC0,
    ETHOSU_PMU_WD_PARSE_STALL_SC1,
    ETHOSU_PMU_WD_PARSE_STALL_SC2,
    ETHOSU_PMU_WD_PARSE_STALL_SC3,
    ETHOSU_PMU_WD_STALLED,
    ETHOSU_PMU_WD_STALLED_BY_WD_BUF,
    ETHOSU_PMU_WD_STALLED_BY_WS,
    ETHOSU_PMU_WD_STALLED_BY_WS_FC,
    ETHOSU_PMU_WD_STALLED_BY_WS_SC0,
    ETHOSU_PMU_WD_STALLED_BY_WS_SC1,
    ETHOSU_PMU_WD_STALLED_BY_WS_SC2,
    ETHOSU_PMU_WD_STALLED_BY_WS_SC3,
    ETHOSU_PMU_WD_STALLED_BY_WS_TC,
    ETHOSU_PMU_WD_TRANS_DW0,
    ETHOSU_PMU_WD_TRANS_DW1,
    ETHOSU_PMU_WD_TRANS_WB,
    ETHOSU_PMU_WD_TRANS_WB0,
    ETHOSU_PMU_WD_TRANS_WB1,
    ETHOSU_PMU_WD_TRANS_WB2,
    ETHOSU_PMU_WD_TRANS_WB3,
    ETHOSU_PMU_WD_TRANS_WBLK,
    ETHOSU_PMU_WD_TRANS_WS,
    ETHOSU_PMU_WD_TRANS_WS_FC,
    ETHOSU_PMU_WD_TRANS_WS_SC0,
    ETHOSU_PMU_WD_TRANS_WS_SC1,
    ETHOSU_PMU_WD_TRANS_WS_SC2,
    ETHOSU_PMU_WD_TRANS_WS_SC3,
    ETHOSU_PMU_WD_TRANS_WS_TC,

    ETHOSU_PMU_SENTINEL // End-marker (not event)
};

#endif /* ETHOSU_PMU_TYPES_H */
